### ISSUE TITLE
Will it be banned for 100 years？

### ISSUE THREAD

**Issue by wutaijieing** [saeed9321/PUBG-JB-Bypass#1]
PUBG New State

**Comment by saeed9321** [comment]
> PUBG New State

This tweak should be enough to avoid ban, however you can test on new account first to confirm.

The main reason I created this tweak was to avoid crash on startup on jailbroken iOS.

**Comment by wutaijieing** [comment]
> > PUBG New State
> 
> This tweak should be enough to avoid ban, however you can test on new account first to confirm.
> 
> The main reason I created this tweak was to avoid crash on startup on jailbroken iOS.


I've tested it.crash in the games
log:
[ExtremeGame_crash_log.txt](https://github.com/saeed9321/PUBG-JB-Bypass/files/7797516/ExtremeGame_crash_log.txt)

**Comment by saeed9321** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > > PUBG New State
> 
> > 
> 
> > This tweak should be enough to avoid ban, however you can test on new account first to confirm.
> 
> > 
> 
> > The main reason I created this tweak was to avoid crash on startup on jailbroken iOS.
> 
> 
> 
> 
> 
> I've tested it.crash in the games
> 
> log:
> 
> [ExtremeGame_crash_log.txt](https://github.com/saeed9321/PUBG-JB-Bypass/files/7797516/ExtremeGame_crash_log.txt)
> 
> 
> 
> 

As per the log, I can see the crash is due to exceeding memory limit.

Can you confirm if it's crashing in every game ?

**Comment by wutaijieing** [comment]
> 

Yes，iPad Pro 12,9 2018 1tb，6g ram

**Comment by wutaijieing** [comment]
> > > > PUBG New State
> > 
> > 
> > > 
> > 
> > 
> > > This tweak should be enough to avoid ban, however you can test on new account first to confirm.
> > 
> > 
> > > 
> > 
> > 
> > > The main reason I created this tweak was to avoid crash on startup on jailbroken iOS.
> > 
> > 
> > I've tested it.crash in the games
> > log:
> > [ExtremeGame_crash_log.txt](https://github.com/saeed9321/PUBG-JB-Bypass/files/7797516/ExtremeGame_crash_log.txt)
> 
> As per the log, I can see the crash is due to exceeding memory limit.
> 
> Can you confirm if it's crashing in every game ?

Yes，iPad Pro 12,9 2018 1tb，6g ram
