### ISSUE TITLE
game updated

### ISSUE THREAD

**Issue by nyxuejiye** [saeed9321/PUBG-JB-Bypass#4]
hello，when update？

**Comment by nyxuejiye** [comment]
10$ want to you can update

**Comment by saeed9321** [comment]
If you mean PUBG New State it’s nearly impossible to bypass the jailbreak detection for the last version as it’s using Promon Shield protection.

Anyway, I will update the tweak if somehow this protection got bypassed.

**Comment by nyxuejiye** [comment]
OK，very thank you❤️❤️





------------------ Original ------------------
From: Saeed9321 ***@***.***&gt;
Date: Fri,Apr 8,2022 10:28 PM
To: saeed9321/PUBG-JB-Bypass ***@***.***&gt;
Cc: nyxuejiye ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [saeed9321/PUBG-JB-Bypass] game updated (Issue #4)





 
If you mean PUBG New State it’s nearly impossible to bypass the jailbreak detection for the last version as it’s using Promon Shield protection.
 
Anyway, I will update the tweak if somehow this protection got bypassed.
